import React,{useState} from 'react';
import {View,TextInput,useWindowDimensions} from 'react-native';
import {useApp} from '../state/AppContext';
import {useTheme} from '../theme';
import {Card,Txt,Icon,Pill,Badge,EmptyState,InfoNote,styles} from '../components/ui';
import {AppAvatar} from '../components/ConnectionRow';
import {filterConnections,summarizeConnections,formatSummaryBytes,formatDuration,getRangeInterval} from '../services/analytics';
export function AppsScreen(){const {dataset,range,openDetail,mode}=useApp();const t=useTheme();const {width}=useWindowDimensions();const [search,setSearch]=useState('');const [sort,setSort]=useState('Most active');const events=filterConnections(dataset,{range});const interval=getRangeInterval(range,dataset.generatedAt);const usage=range==='Live'?[]:(dataset.appUsage??[]).filter(row=>row.dayStart>=interval.start&&row.dayStart<=interval.end);const apps=dataset.apps.filter(a=>a.name.toLowerCase().includes(search.toLowerCase())).map(app=>({app,stats:summarizeConnections(events.filter(e=>e.appId===app.id)),usageSeconds:usage.filter(row=>row.appId===app.id).reduce((sum,row)=>sum+row.durationSeconds,0)})).sort((a,b)=>sort==='Largest uploads'?b.stats.uploaded-a.stats.uploaded:sort==='Name'?a.app.name.localeCompare(b.app.name):b.stats.connections-a.stats.connections||b.usageSeconds-a.usageSeconds);
 return <View style={styles.stack}><View style={{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:12}}><View style={{flexDirection:'row',alignItems:'center',gap:10,backgroundColor:t.surface,borderColor:t.border,borderWidth:1,borderRadius:11,paddingHorizontal:14,flex:1,minWidth:200}}><Icon name="search" size={16}/><TextInput accessibilityLabel="Search apps" placeholder="Find an application" placeholderTextColor={t.subtle} value={search} onChangeText={setSearch} style={{height:46,flex:1,color:t.text,fontSize:13}}/></View>{(mode==='device'?['Most active','Name']:['Most active','Largest uploads','Name']).map(s=><Pill key={s} label={s} active={sort===s} onPress={()=>setSort(s)}/>)}</View>
 <View style={{flexDirection:'row',flexWrap:'wrap',gap:16}}>{apps.map(({app,stats,usageSeconds})=><Card key={app.id} onPress={()=>openDetail({type:'app',id:app.id})} style={{width:width>1200?'31.8%':width>730?'48.5%':'100%'}}><View style={styles.between}><AppAvatar app={app} size={49}/><Icon name="arrow-up-right" size={18}/></View><Txt size={19} weight="600" style={{marginTop:19}}>{app.name}</Txt><Txt size={12} color={t.muted}>{app.category}</Txt><View style={{flexDirection:'row',marginTop:23,marginBottom:18}}><View style={{flex:1}}><Txt size={22}>{app.source==='device-activity'?formatDuration(usageSeconds):stats.connections}</Txt><Txt size={10} color={t.muted}>{app.source==='device-activity'?'Foreground time':mode==='device'?'Domain records':'Connections'}</Txt></View><View style={{flex:1}}><Txt size={mode==='device'?14:22}>{mode==='device'&&!stats.measuredTransfers?'Unavailable':formatSummaryBytes(stats,'up')}</Txt><Txt size={10} color={t.muted}>Uploaded</Txt></View></View><View style={{height:3,backgroundColor:t.elevated,borderRadius:3}}><View style={{height:3,width:`${Math.max(5,(app.source==='device-activity'?usageSeconds/Math.max(1,usage.reduce((sum,row)=>sum+row.durationSeconds,0)):stats.connections/Math.max(1,events.length))*100)}%`,backgroundColor:app.color,borderRadius:3}}/></View><View style={{...styles.between,marginTop:14}}><Txt size={11} color={t.muted}>{app.source==='device-activity'?'Android UsageStats':`${stats.organizations} ${mode==='device'?'reported owners':'organizations'}`}</Txt><Badge state={mode==='device'?'Confirmed':'Observed'}/></View></Card>)}</View>
 {!apps.length&&<EmptyState title={mode==='device'?'No app profiles available':'No matching applications'} description={mode==='device'?'Import an Apple App Privacy Report or grant Android Usage Access in Settings, then try another app name.':'Try a different app name.'} icon="grid"/>}<InfoNote>{mode==='demo'?'These are sample application profiles, not an inventory of the apps installed on your device.':'Profiles come from imported Apple report bundle identifiers or Android daily usage. They are not a complete inventory of installed apps; transfer amounts are unavailable.'}</InfoNote></View>;
}
