import React,{useState,useEffect} from 'react';
import {View,TextInput,ScrollView} from 'react-native';
import {useApp} from '../state/AppContext';
import {useTheme} from '../theme';
import {Card,Txt,Icon,SectionHeading,Metric,Pill,Button,Badge,EmptyState,InfoNote,styles} from '../components/ui';
import {NetworkCore} from '../components/NetworkCore';
import {createCapture,updateCapture,finishCapture,compareCaptures,createImportedSnapshot} from '../services/capture';
import {formatBytes,formatDuration} from '../services/analytics';

export function CapturesScreen(){const {mode,dataset,activeCapture,setActiveCapture,captures,saveCapture,openDetail,settings,toast,navigate}=useApp();const t=useTheme();const [appId,setAppId]=useState<string|null>(null);const [name,setName]=useState('');const [now,setNow]=useState(activeCapture?.startedAt??0);const [compare,setCompare]=useState<string[]>([]);
 useEffect(()=>{if(!activeCapture)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[activeCapture]);
 const live=activeCapture?updateCapture(activeCapture,dataset,now):null;
 const start=()=>{if(mode!=='demo'){navigate('Trust');return;}const capture=createCapture(mode,appId);setActiveCapture({...capture,name:name.trim()||`${appId?dataset.apps.find(a=>a.id===appId)?.name:'All apps'} capture`});setNow(Date.now());};
 const saveSnapshot=()=>{try{const snapshot=createImportedSnapshot(dataset,appId,name.trim()||`${appId?dataset.apps.find(a=>a.id===appId)?.name:'All apps'} report snapshot`);saveCapture(snapshot);toast('Historical report snapshot saved on this device.');openDetail({type:'capture',id:snapshot.id});}catch(error){toast(error instanceof Error?error.message:'Could not save a report snapshot.');}};
 const stop=()=>{if(!activeCapture)return;const saved=finishCapture(activeCapture,dataset,Date.now());saveCapture(saved);setActiveCapture(null);toast('Capture saved on this device.');openDetail({type:'capture',id:saved.id});};
 const before=captures.find(c=>c.id===compare[0]);const after=captures.find(c=>c.id===compare[1]);const comparison=before&&after&&before.mode===after.mode&&(before.kind??'demo')===(after.kind??'demo')?compareCaptures(before,after):null;
 return <View style={styles.stack}>
  {live?<Card><View style={styles.between}><View style={styles.row}><View style={{width:8,height:8,borderRadius:4,backgroundColor:t.cyan}}/><Txt size={12} color={t.cyan} weight="600">DEMO CAPTURE IN PROGRESS</Txt></View><Badge state="Observed"/></View><View style={{alignItems:'center',paddingVertical:20}}><NetworkCore size={190} light={settings.light} reducedMotion={settings.reducedMotion}/><Txt size={46} weight="400" style={{letterSpacing:-2}}>{formatDuration((now-live.startedAt)/1000)}</Txt><Txt size={13} color={t.muted}>{live.name}</Txt></View><View style={styles.wrap}><Metric label="Connections" value={live.summary.connections}/><Metric label="Uploaded" value={formatBytes(live.summary.uploaded)}/><Metric label="Organizations" value={live.summary.organizations}/></View><InfoNote>This demo replays sample events. No activity from your device or other apps is being recorded.</InfoNote><Button label="Finish & save capture" icon="square" onPress={stop}/>{live.connections.length>0&&<View style={{marginTop:24}}><SectionHeading title="During this capture"/>{live.connections.slice(-4).reverse().map(e=><View key={e.id} style={{paddingVertical:10,borderBottomWidth:1,borderColor:t.border}}><Txt size={13}>{dataset.apps.find(a=>a.id===e.appId)?.name??'App'} → {e.domain}</Txt><Txt size={11} color={t.muted}>↑ {formatBytes(e.bytesUploaded)} · {e.category}</Txt></View>)}</View>}</Card>:
  <Card><View style={{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:20}}><View style={{flex:1,minWidth:230}}><View style={{flexDirection:'row',gap:8,alignItems:'center',marginBottom:16}}><Icon name="aperture" color={t.blue}/><Txt size={11} color={t.blue} weight="600" style={{letterSpacing:1.4}}>A CLOSER LOOK</Txt></View><Txt size={30} weight="500" style={{letterSpacing:-.8}}>A moment of activity.{"\n"}A clearer picture.</Txt><Txt size={13} color={t.muted} style={{marginTop:14,maxWidth:460,lineHeight:21}}>{mode==='demo'?'Capture a focused observation period. See the connections, organizations, and background activity together in one report.':'Save a snapshot of an imported Apple report to compare its historical domain and sensor records later.'}</Txt></View><NetworkCore size={185} active={false} light={settings.light}/></View><View style={{height:1,backgroundColor:t.border,marginVertical:23}}/><Txt size={12} color={t.muted} style={{marginBottom:10}}>Focus on an app</Txt><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,paddingBottom:16}}><Pill label="All apps" active={appId===null} onPress={()=>setAppId(null)}/>{dataset.apps.filter(a=>mode==='demo'||a.source==='user-import').map(a=><Pill key={a.id} label={a.name} active={appId===a.id} onPress={()=>setAppId(a.id)}/>)}</ScrollView><TextInput value={name} onChangeText={setName} placeholder="Capture name (optional)" placeholderTextColor={t.subtle} accessibilityLabel="Capture name" style={{height:46,paddingHorizontal:14,borderRadius:10,borderWidth:1,borderColor:t.border,color:t.text,backgroundColor:t.background,marginBottom:17}}/><Button label={mode==='demo'?'Start demo capture':dataset.connections.length||dataset.sensors.length?'Save imported snapshot':'Import a report'} icon="aperture" onPress={mode==='demo'?start:dataset.connections.length||dataset.sensors.length?saveSnapshot:()=>navigate('Settings')}/><InfoNote>{mode==='demo'?'A guided replay of sample events. Leave this screen and return when you are ready to finish. Captures stay local.':'This creates a historical report snapshot, not a live recording. Apple domain rows summarize contacts over a rolling window; upload amounts and app foreground state remain unavailable.'}</InfoNote></Card>}
  <SectionHeading title="Saved captures" subtitle="Local snapshots you can return to" action={captures.filter(c=>c.mode===mode).length>=2?'Compare two':undefined} onAction={()=>{setCompare(captures.filter(c=>c.mode===mode).slice(0,2).reverse().map(c=>c.id));}}/>
  {comparison&&before&&after&&<Card><SectionHeading title="Side by side" subtitle={`${before.name} → ${after.name}`} action="Close" onAction={()=>setCompare([])}/>{[['Connections',before.summary.connections,after.summary.connections],['Uploaded',before.kind==='report-snapshot'?'Unavailable':formatBytes(before.summary.uploaded),after.kind==='report-snapshot'?'Unavailable':formatBytes(after.summary.uploaded)],['Organizations',before.summary.organizations,after.summary.organizations],['Marketing endpoints',before.kind==='report-snapshot'?'Unclassified':before.summary.marketing,after.kind==='report-snapshot'?'Unclassified':after.summary.marketing],['Background events',before.kind==='report-snapshot'?'Unavailable':before.summary.background,after.kind==='report-snapshot'?'Unavailable':after.summary.background]].map(([label,a,b])=><View key={label} style={{...styles.between,paddingVertical:13,borderBottomWidth:1,borderColor:t.border}}><Txt size={13} color={t.muted}>{label}</Txt><View style={styles.row}><Txt size={15}>{a}</Txt><Icon name="arrow-right" size={14}/><Txt size={15} color={t.blue}>{b}</Txt></View></View>)}<InfoNote>{comparison.newDomains.length} newly seen domains. {before.kind==='report-snapshot'?'Imported reports may have overlapping rolling windows; compare domain sets, not inferred traffic totals.':'Compare captures of similar duration and app activity for useful context.'}</InfoNote></Card>}
  {captures.length?captures.map(c=><Card key={c.id}><View style={styles.between}><View style={styles.row}><View style={{width:42,height:42,borderRadius:12,backgroundColor:t.blueTint,alignItems:'center',justifyContent:'center'}}><Icon name="aperture" color={t.blue}/></View><View><Txt weight="600">{c.name}</Txt><Txt size={11} color={t.muted}>{new Date(c.startedAt).toLocaleDateString()} · {c.kind==='report-snapshot'?'Historical Apple report snapshot':`${formatDuration(((c.endedAt??c.startedAt)-c.startedAt)/1000)} · ${c.mode==='demo'?'Sample data':'Device data'}`}</Txt></View></View></View><View style={{flexDirection:'row',gap:20,marginVertical:19}}><Txt size={12} color={t.muted}>{c.summary.connections} {c.kind==='report-snapshot'?'domain records':'connections'}</Txt><Txt size={12} color={t.muted}>↑ {c.kind==='report-snapshot'?'Unavailable':formatBytes(c.summary.uploaded)}</Txt></View><View style={styles.between}><Button small label="Open report" icon="arrow-up-right" variant="secondary" onPress={()=>openDetail({type:'capture',id:c.id})}/><Pill label={compare.includes(c.id)?'Selected':'Compare'} active={compare.includes(c.id)} onPress={()=>setCompare(prev=>prev.includes(c.id)?prev.filter(x=>x!==c.id):[...prev.slice(-1),c.id])}/></View></Card>):<EmptyState title="Your first capture starts here" description="Saved captures help you understand changes over time. Give your next observation a name, and keep it for later." icon="aperture"/>}
 </View>;
}
