import React,{useState} from 'react';
import {View,TextInput,ScrollView,useWindowDimensions} from 'react-native';
import {useApp} from '../state/AppContext';
import {useTheme} from '../theme';
import {Card,Txt,Icon,SectionHeading,Metric,Pill,Button,InfoNote,EmptyState,styles} from '../components/ui';
import {ConnectionRow} from '../components/ConnectionRow';
import {filterConnections,summarizeConnections,formatSummaryBytes} from '../services/analytics';

export function ConnectionsScreen({live=false,marketing=false}:{live?:boolean;marketing?:boolean}){
 const {dataset,range,mode,demoPaused,setDemoPaused,navigate}=useApp();const t=useTheme();const {width}=useWindowDimensions();
 const [search,setSearch]=useState('');const [filter,setFilter]=useState('All');const [limit,setLimit]=useState(30);const [sort,setSort]=useState<'recent'|'upload'>('recent');
 const base=filterConnections(dataset,{range:live?'Live':range,search});
 const events=base.filter(e=>(!marketing||(mode==='device'?e.potentialTracker:['Advertising','Analytics','Attribution','Marketing'].includes(e.category)))&&(filter==='All'||(filter==='Background'?e.foregroundState==='background':filter==='New destinations'?e.isNewDestination:filter==='Large transfers'?e.bytesMeasured!==false&&e.bytesUploaded>500000:filter==='Unknown'?e.category==='Unknown':filter==='Potential cross-app'?e.potentialTracker:e.category===filter))).sort((a,b)=>sort==='upload'?b.bytesUploaded-a.bytesUploaded:b.timestamp-a.timestamp);
 const summary=summarizeConnections(events);
 return <View style={styles.stack}>
  {live&&<Card style={{flexDirection:'row',alignItems:'center',gap:14,padding:17}}><View style={{width:9,height:9,borderRadius:5,backgroundColor:mode==='demo'&&!demoPaused?t.cyan:t.amber}}/><View style={{flex:1}}><Txt size={14} weight="600">{mode==='demo'?(demoPaused?'Demo feed paused':'A window into your network'):'Live monitoring unavailable'}</Txt><Txt size={12} color={t.muted}>{mode==='demo'?'Recent sample events · not live device traffic':'Imported report rows are historical. A native observation provider is required for live traffic.'}</Txt></View>{mode==='demo'&&<Button small label={demoPaused?'Resume':'Pause'} icon={demoPaused?'play':'pause'} variant="secondary" onPress={()=>setDemoPaused(!demoPaused)}/>}</Card>}
  {marketing&&<Card style={{backgroundColor:t.amberTint,borderColor:t.amberTint}}><View style={styles.row}><Icon name="eye" color={t.amber}/><Txt size={18} weight="500">Understand the connections behind the scenes.</Txt></View><Txt size={13} color={t.muted} style={{marginTop:12}}>{mode==='device'?'Apple marked these domains as potentially collecting information across apps or sites. That flag does not prove tracking, marketing use, or what a contact contained.':'These endpoints are associated with marketing services. A connection does not prove that personal information was collected or that an advertisement was selected because of it.'}</Txt></Card>}
  <View style={styles.wrap}><Metric label={mode==='device'?'Domain records':'Connections'} value={summary.connections} icon="git-branch" state={mode==='device'?'Confirmed':'Observed'}/><Metric label="Uploaded" value={formatSummaryBytes(summary,'up')} icon="arrow-up-right" state={summary.measuredTransfers===0?'Unavailable':'Observed'}/><Metric label={mode==='device'?'Reported owners':'Organizations'} value={summary.organizations} icon="globe" state={mode==='device'?'Confirmed':'Observed'}/>{width>700&&<Metric label="In background" value={mode==='device'?'Unavailable':summary.background} icon="layers" state={mode==='device'?'Unavailable':'Observed'}/>}</View>
  <Card>
   <SectionHeading title={marketing?(mode==='device'?'Apple potential cross-app flags':'Marketing & analytics endpoints'):live?'Connection feed':mode==='device'?'Reported domain contacts':'Data leaving your phone'} subtitle={`${events.length} ${mode==='device'?'domain records':'connections'} in this view`} action={mode==='device'?undefined:sort==='recent'?'Sort by upload':'Sort by recent'} onAction={()=>setSort(sort==='recent'?'upload':'recent')}/>
   <View style={{flexDirection:'row',gap:10,alignItems:'center',paddingHorizontal:14,height:45,backgroundColor:t.background,borderRadius:10,borderWidth:1,borderColor:t.border,marginBottom:16}}><Icon name="search" size={16}/><TextInput accessibilityLabel="Search connections" placeholder="Search an app, company, domain, or IP" placeholderTextColor={t.subtle} value={search} onChangeText={v=>{setSearch(v);setLimit(30);}} style={{color:t.text,fontSize:13,flex:1,height:44}}/></View>
   <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,paddingBottom:14}}>{(mode==='device'?['All','Potential cross-app','Unknown']:marketing?['All','Analytics','Advertising','Attribution','Background']:['All','Background','Analytics','Advertising','Unknown','Large transfers','New destinations']).map(f=><Pill key={f} label={f} active={filter===f} onPress={()=>{setFilter(f);setLimit(30);}}/>)}</ScrollView>
   {events.length?events.slice(0,limit).map(e=><ConnectionRow key={e.id} event={e}/>):<EmptyState title="No domain records to show" description={mode==='device'?'Import an Apple App Privacy Report in Settings or choose a different range. Live monitoring is not connected.':'Try another filter, search, or time period.'} icon="git-branch"/>}
   {events.length>limit&&<View style={{marginTop:16}}><Button label={`Show more · ${events.length-limit} remaining`} variant="secondary" onPress={()=>setLimit(v=>v+30)}/></View>}
  </Card>
  <InfoNote>{mode==='device'?'Each imported Apple row summarizes contacts with a domain; its timestamp is the latest contact. Bytes, IP addresses, country, foreground state, and payload contents are unavailable.':'IPward shows destinations and transfer metadata in the sample preview. Encrypted payload contents are unavailable. All events in this workspace are illustrative.'}</InfoNote>
  {marketing&&<Card><SectionHeading title="Why am I seeing this ad?" subtitle="Look at timing, without guessing causation"/><Txt size={13} color={t.muted}>Compare the connections in this time range with activity around an advertisement. IPward cannot prove why a specific ad was selected.</Txt><View style={{marginTop:16,alignSelf:'flex-start'}}><Button label="View activity timeline" icon="clock" variant="secondary" onPress={()=>navigate('Activity')}/></View></Card>}
 </View>;
}
