import React, { useState } from 'react';
import { Platform, Pressable, View } from 'react-native';
import { Badge, Button, Card, Icon, InfoNote, SectionHeading, styles, Txt } from '../components/ui';
import { useApp } from '../state/AppContext';
import { useTheme } from '../theme';
import { CAPABILITY_KEYS, getCapabilities } from '../services/capabilities';

const evidence = [
  { state: 'Confirmed', description: 'A value supplied by an authorized API, integration, or authoritative source. In Demo, it is an illustration of that source.' },
  { state: 'Observed', description: 'An event directly detected by a supported monitoring source. Sample observations are fictional and never collected from this device.' },
  { state: 'Estimated', description: 'An inference with identifiable input signals, confidence, timestamp, and algorithm version. An estimate is not a measured fact.' },
  { state: 'Unavailable', description: 'The operating system, permissions, or this build do not provide enough evidence. Missing data is never silently filled with a guess.' },
];

export function TrustScreen() {
  const t = useTheme();
  const { mode, setMode, settings, navigate, openDetail, dataset, usageAccess } = useApp();
  const [expanded, setExpanded] = useState<string | null>('networkMonitoring');
  const capabilities = getCapabilities(Platform.OS, 'device', usageAccess === 'authorized');
  const retention = settings.retention === 0 ? 'until you delete them' : `for up to ${settings.retention} days`;
  return <View style={styles.stack}>
    <Card style={{ padding: 27, backgroundColor: t.blueTint, borderColor: t.blueTint }}>
      <View style={{ ...styles.row, marginBottom: 16 }}><Icon name="eye" size={24} color={t.blue} /><Txt size={12} color={t.blue} weight="600" style={{ letterSpacing: 1.8 }}>TRUST & TRANSPARENCY</Txt></View>
      <Txt size={27} weight="500" style={{ maxWidth: 630, letterSpacing: -0.7 }}>A clear view. An honest boundary.</Txt>
      <Txt size={14} color={t.muted} style={{ marginTop: 12, maxWidth: 670 }}>IPward helps you understand observable activity. Every insight should tell you where it came from, how certain it is, and what it cannot reveal.</Txt>
      <View style={{ marginTop: 24, gap: 12, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center' }}><Button label={mode === 'demo' ? 'Switch to device mode' : 'Explore demo mode'} icon={mode === 'demo' ? 'smartphone' : 'play'} variant="secondary" onPress={() => setMode(mode === 'demo' ? 'device' : 'demo')} /><Txt size={12} color={t.muted}>{mode === 'demo' ? 'You are viewing fictional sample activity.' : dataset.connections.length || dataset.sensors.length ? 'Device mode · Historical Apple report imported. No live monitoring.' : 'Device mode · No live network or sensor adapter connected.'}</Txt></View>
    </Card>
    <View><SectionHeading title="Know the evidence" subtitle="Source and certainty are always separate" /><View style={styles.wrap}>{evidence.map(item => <Card key={item.state} onPress={() => openDetail({ type: 'evidence', id: item.state })} style={{ flex: 1, minWidth: 230 }}><Badge state={item.state} /><Txt size={13} color={t.muted} style={{ marginTop: 12 }}>{item.description}</Txt></Card>)}</View></View>
    <Card>
      <SectionHeading title="What this build can access" subtitle={`${Platform.OS === 'ios' ? 'iOS' : Platform.OS === 'android' ? 'Android' : 'Web preview'} · Real-device capabilities`} />
      <Txt size={13} color={t.muted} style={{ marginBottom: 19 }}>Apple report import is available on all platforms. Android app-use aggregates require a development build and explicit Usage Access. No live network or sensor-monitoring adapter is integrated.</Txt>
      {CAPABILITY_KEYS.map(key => {
        const capability = capabilities[key];
        return <View key={key} style={{ borderTopWidth: 1, borderColor: t.border }}><Pressable accessibilityRole="button" accessibilityState={{ expanded: expanded === key }} onPress={() => setExpanded(expanded === key ? null : key)} style={{ ...styles.between, minHeight: 61 }}><Txt size={13} weight="500" style={{ flex: 1 }}>{capability.title}</Txt><Badge state={capability.available ? 'Confirmed' : 'Unavailable'} /><Icon name={expanded === key ? 'chevron-up' : 'chevron-down'} size={15} /></Pressable>{expanded === key && <Txt size={12} color={t.muted} style={{ paddingBottom: 18, paddingRight: 24 }}>{capability.reason}</Txt>}</View>;
      })}
    </Card>
    <View style={styles.wrap}>
      <Card style={{ flex: 1, minWidth: 260 }}><SectionHeading title="What stays local" subtitle="Data policy for this build" /><View style={{ gap: 20 }}><View style={{ ...styles.row, alignItems: 'flex-start' }}><Icon name="hard-drive" color={t.cyan} /><View style={{ flex: 1 }}><Txt size={14} weight="500">Preferences, reports, and imported events</Txt><Txt size={12} color={t.muted} style={{ marginTop: 5 }}>Saved in app-local storage. Imported events use SQLite on mobile; reports and preferences use local storage. Imports and captures are kept {retention}. Android usage is read on demand from the OS.</Txt></View></View><View style={{ ...styles.row, alignItems: 'flex-start' }}><Icon name="cpu" color={t.cyan} /><View style={{ flex: 1 }}><Txt size={14} weight="500">Classification and summaries</Txt><Txt size={12} color={t.muted} style={{ marginTop: 5 }}>Demo classifications use bundled example rules. Imported contacts remain unclassified except for Apple’s separately displayed potential cross-app flag. No classification backend is connected.</Txt></View></View><View style={{ ...styles.row, alignItems: 'flex-start' }}><Icon name="lock" color={t.cyan} /><View style={{ flex: 1 }}><Txt size={14} weight="500">Storage boundaries</Txt><Txt size={12} color={t.muted} style={{ marginTop: 5 }}>Local app storage is not an encrypted evidence vault. This build adds no database encryption. Device and browser storage protections still apply.</Txt></View></View></View><View style={{ marginTop: 22 }}><Button label="Manage storage & retention" variant="secondary" onPress={() => navigate('Settings')} /></View></Card>
      <Card style={{ flex: 1, minWidth: 260 }}><SectionHeading title="What leaves IPward" subtitle="Explicit choices, visible boundaries" /><View style={{ gap: 20 }}><View style={{ ...styles.row, alignItems: 'flex-start' }}><Icon name="cloud-off" color={t.blue} /><View style={{ flex: 1 }}><Txt size={14} weight="500">No activity sync service</Txt><Txt size={12} color={t.muted} style={{ marginTop: 5 }}>This build has no account, cloud history sync, advertising service, or activity-upload backend. Local-only processing is the current behavior.</Txt></View></View><View style={{ ...styles.row, alignItems: 'flex-start' }}><Icon name="share" color={t.blue} /><View style={{ flex: 1 }}><Txt size={14} weight="500">Exports are your choice</Txt><Txt size={12} color={t.muted} style={{ marginTop: 5 }}>Reports can contain domains, times, and other sensitive metadata. You decide where an exported file goes.</Txt></View></View><View style={{ ...styles.row, alignItems: 'flex-start' }}><Icon name="mail" color={t.blue} /><View style={{ flex: 1 }}><Txt size={14} weight="500">Optional email integration</Txt><Txt size={12} color={t.muted} style={{ marginTop: 5 }}>Not connected. A future provider integration would require your explicit authorization and a clear explanation of metadata access. Nothing here reads email bodies.</Txt></View></View></View></Card>
    </View>
    <Card><SectionHeading title="How an insight is made" /><View style={{ gap: 20 }}><View><Txt size={14} weight="600">Classification describes an endpoint</Txt><Txt size={13} color={t.muted} style={{ marginTop: 7 }}>A company can operate advertising, authentication, cloud, and content delivery services. IPward matches the specific domain to a bundled rule, with a category and confidence. A company name alone does not establish the purpose of a connection.</Txt></View><View><Txt size={14} weight="600">Estimates preserve uncertainty</Txt><Txt size={13} color={t.muted} style={{ marginTop: 7 }}>The estimation foundation keeps input signals and derived results separate. Without eligible, correlated signals, the result is Unavailable. Traffic totals and notification counts are insufficient to count private messages.</Txt></View><View><Txt size={14} weight="600">A destination is not a data policy</Txt><Txt size={13} color={t.muted} style={{ marginTop: 7 }}>A network destination’s location describes an endpoint, not where personal data is stored. Shared infrastructure does not identify the ultimate recipient. Encrypted payload contents are unavailable.</Txt></View><View><Txt size={14} weight="600">An access event is not a recording</Txt><Txt size={13} color={t.muted} style={{ marginTop: 7 }}>Microphone or camera access does not prove what was captured, why it was used, or whether it was transmitted. Permission status is also distinct from actual access.</Txt></View></View></Card>
    <Card><SectionHeading title="Built with open tools" subtitle="Open-source acknowledgements" /><Txt size={13} color={t.muted}>IPward uses React, React Native, Expo, Expo Router, React Native SVG, SQLite, DocumentPicker, FileSystem, and AsyncStorage. Dependency versions and licenses are recorded with the project’s package files. No independent security audit has been completed for this build.</Txt></Card>
    <InfoNote>IPward never needs your microphone, camera, contacts, or messages to show the sample experience. Permission prompts should only appear when a real feature can explain and use the requested access.</InfoNote>
  </View>;
}
