import React from 'react';
import {View,Pressable,useWindowDimensions} from 'react-native';
import {AppProfile,ConnectionEvent} from '../types';
import {useApp} from '../state/AppContext';
import {useTheme} from '../theme';
import {Icon,IconName,Txt} from './ui';
import {formatEventBytes,formatTime} from '../services/analytics';
export function AppAvatar({app,size=39}:{app?:AppProfile;size?:number}) {const t=useTheme();const icons:Record<string,IconName>={instagram:'instagram',spotify:'music',safari:'compass',messages:'message-circle',whatsapp:'phone',weather:'cloud',mail:'mail',notion:'file-text',game:'grid'}; const icon=icons[app?.id??''];return <View style={{width:size,height:size,borderRadius:size*.27,backgroundColor:(app?.color??t.blue)+'20',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:(app?.color??t.blue)+'28'}}>{icon?<Icon name={icon} size={size*.46} color={app?.color??t.blue}/>:<Txt color={app?.color??t.blue} size={size*.32} weight="600">{app?.initials??'?'}</Txt>}</View>;}
export function ConnectionRow({event,compact=false}:{event:ConnectionEvent;compact?:boolean}) {const {dataset,openDetail}=useApp();const t=useTheme();const {width}=useWindowDimensions();const app=dataset.apps.find(a=>a.id===event.appId);const org=dataset.organizations.find(o=>o.id===event.organizationId);const marketing=['Analytics','Advertising','Attribution','Marketing'].includes(event.category);return <Pressable accessibilityRole="button" accessibilityLabel={`${app?.name??'Unattributed app'} to ${org?.name??event.domain}, ${event.bytesMeasured===false?`${event.reportHits??1} reported contacts; transfer bytes unavailable`:`${formatEventBytes(event,'up')} uploaded`}`} onPress={()=>openDetail({type:'connection',id:event.id})} style={({pressed,hovered}:any)=>({flexDirection:'row',gap:12,paddingVertical:15,alignItems:'center',borderBottomWidth:1,borderBottomColor:t.border,backgroundColor:pressed||hovered?t.elevated:'transparent'})}><AppAvatar app={app}/><View style={{flex:1,minWidth:0}}><View style={{flexDirection:'row',alignItems:'center',gap:7}}><Txt size={13} weight="500">{app?.name??'Unattributed'}</Txt><Icon name="arrow-right" size={12} color={t.subtle}/><Txt numberOfLines={1} size={12} color={t.muted} style={{flexShrink:1}}>{org?.name??'Unknown'}</Txt></View><Txt numberOfLines={1} size={11} color={t.subtle} style={{marginTop:4}}>{event.domain}</Txt></View>{!compact&&width>760&&<View style={{width:125}}><Txt size={11} color={marketing?t.amber:t.muted}>{event.potentialTracker?'Potential cross-app collection':event.category}</Txt><Txt size={10} color={t.subtle}>{event.foregroundState==='background'?'In background':event.foregroundState==='foreground'?'In use':'App state unknown'}</Txt></View>}<View style={{alignItems:'flex-end',gap:3}}><Txt size={12} color={t.text}>{event.bytesMeasured===false?`${event.reportHits??1} contacts`:`↑ ${formatEventBytes(event,'up')}`}</Txt><Txt size={10} color={t.subtle}>{formatTime(event.timestamp)}</Txt></View>{!compact&&width>650&&<Icon name="chevron-right" size={15}/>}</Pressable>;}
